### ISSUE TITLE
error: 4788 bytes of body are still expected ( error in cloning )

### ISSUE THREAD

**Issue by Anasselouarrak** [TijClass/Booking_Excalibur#17]
I can't clone the starters files from repository , someone gives me an idea !!!

- Receiving objects:  89% (66/74), 28.90 MiB | 13.00 KiB/s
  error: 4788 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: index-pack failed

**Comment by Anasselouarrak** [comment]
Solved !!!

**Comment by rosbeef** [comment]
do you remember how?
